name: snow_portfolio
version: 0.1.0
publish_to: none
description: "Alexander Nieves' resume."
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  gap: ^3.0.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  lottie: ^2.7.0
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.2.2
  card_swiper: ^3.0.1
  font_awesome_flutter: ^10.6.0
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  dev_icons: ^1.0.0
  google_fonts: ^6.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/projects/
  uses-material-design: true

flutter_launcher_icons: 
  web: 
    image_path: assets/icons/launch-icon.png
    generate: true

flutter_native_splash: 
  color: '#212121'
  image: assets/icons/splash-icon.png
  web: true

