name: snow_portfolio
version: 0.2.0
publish_to: none
description: "Alexander Nieves' portfolio."
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  gap: ^3.0.1
  flutter:
    sdk: flutter
  lottie: ^3.0.0
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.2.2
  card_swiper: ^3.0.1
  font_awesome_flutter: ^10.6.0
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  intl: ^0.18.1
  dev_icons: ^1.0.0
  google_fonts: ^6.1.0
  flutter_localizations:
    sdk: flutter
  slang: ^3.28.0
  slang_flutter: ^3.28.0
  scrollable_positioned_list: ^0.3.8
  feedback: ^3.0.0
  go_router: ^13.1.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get_it: ^7.6.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  slang_build_runner: ^3.28.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/projects/
  uses-material-design: true

# dart run flutter_launcher_icons:main
flutter_launcher_icons:
  image_path: "assets/icons/logo.png"
  web:
    generate: true

# Customize the parameters below, and run the following command in the terminal:
# dart run flutter_native_splash:create
flutter_native_splash:
  web: true

  color: "#ffffff"
  image: assets/icons/splash-icon.png
  # Dark mode
  color_dark: "#131516"
