name: Launch Web

on:
  push:
    branches: [ main ]
    paths:
      - 'snow_portfolio/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.8"
          channel: "stable"
      - run: flutter pub get
        working-directory: snow_portfolio
      - run: flutter build web --web-renderer canvaskit --release
        working-directory: snow_portfolio
      - run: cp -r snow_portfolio/build/web/* docs # Comando para copiar el contenido de build/web a docs
      - run: cp snow_portfolio/assets/google51501707e62fe96b.html docs/google51501707e62fe96b.html
      - run: flutter clean
        working-directory: snow_portfolio
      - run: git add .
      - run: git config user.name github-actions # Comando para configurar el nombre de usuario de git
      - run: git config user.email github-actions@github.com # Comando para configurar el email de usuario de git
      - run: git commit -m "Deploy web to GitHub Pages" # Comando para hacer un commit con un mensaje
      - run: git push https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/AlexitoSnow/alexitosnow.github.io.git main
